#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:

set=$#

if [ "$set" -lt 4 ]; then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY">&2
	exit 1;
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
