#!/bin/bash

# Check if the number of arguments is less than 3
if [ "$#" -lt 3 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

# Path to the file to be transferred
file_path="$1"

# IP of the server
server_ip="$2"

# Username for scp
username="$3"

# Path to SSH private key (if provided)
ssh_key=""
if [ "$#" -eq 4 ]; then
  ssh_key="-i $4"
fi

# Disable strict host key checking for scp
scp_options="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $ssh_key $scp_options "$file_path" "$username@$server_ip:~/"

