#!/usr/bin/env bash
# Update the system

sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy to start at boot
sudo systemctl enable haproxy

# Backup the original configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

ha_config="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 350704-web-01 52.86.222.148:80 check
    server 350704-web-02 3.85.41.223:80 check
"
echo "$ha_config" | sudo tee /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo systemctl restart haproxy

