#!/usr/bin/env bash
# compress the databases into .tgz files

# Check if password argument is provided
if [ $# -eq 0 ]; then
    echo "No arguments supplied. Please provide the MySQL root password."
    exit 1
fi

# Set the MySQL root password from the first argument
mysql_password=$1

# Generate the current date in the desired format
date_format=$(date +"%d-%m-%Y")

# MySQL dump filename
dump_filename="backup.sql"

# Compressed archive filename
archive_filename="${date_format}.tar.gz"

# MySQL dump command
mysqldump_command="sudo mysqldump --all-databases -p${mysql_password} > ${dump_filename}"

# Run the MySQL dump command and check if it was successful
if ! eval "${mysqldump_command}"; then
        echo "MySQL dump failed. Check the MySQL password or the mysqldump command."
        exit 1
fi

# Create a compressed archive
tar -czf "${archive_filename}" "${dump_filename}"

