#!/usr/bin/env bash
# Check if password is supplied

if [ -z "$1" ]
then
    echo "Please provide the MySQL root password as an argument."
    exit 1
fi

# MySQL user credentials
USER='root'
PASSWORD="$1"

# File names
SQL_FILE='backup.sql'
ARCHIVE_FILE=$(date +%d-%m-%Y).tar.gz

# Dump all databases
mysqldump --user=${USER} --password="${PASSWORD}" --all-databases > "${SQL_FILE}"

# Create a compressed archive
tar -czvf "${ARCHIVE_FILE}" "${SQL_FILE}"
