#!/usr/bin/env bash
# compress the databases into .tgz files

# Set the MySQL root password to empty string
mysql_password=""

# Generate the current date in the desired format
date_format=$(date +"%d-%m-%Y")

# MySQL dump filename
dump_filename="backup.sql"

# Compressed archive filename
archive_filename="${date_format}.tar.gz"

# MySQL dump command
mysqldump_command="sudo mysqldump"

# Add password to mysqldump command if not empty
if [ -n "${mysql_password}" ]; then
    mysqldump_command+=" -p${mysql_password}"
fi

mysqldump_command+=" --all-databases > ${dump_filename}"

# Run the MySQL dump command
eval "${mysqldump_command}"

# Check if mysqldump was successful
if ! eval "${mysqldump_command}"; then
	echo "MySQL dump failed. Check the MySQL password or the mysqldump command."
	exit 1
fi
# Create a compressed archive
tar -czf "${archive_filename}" "${dump_filename}"
