#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 80


#configure nginx to listen on port 80 for all available ip4 ip6
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart the system
sudo service nginx restart
