#!/usr/bin/env bash
# Update package list and install Nginx

apt-get update
apt-get install -y nginx

# Check Nginx status
nginx_status=$(systemctl is-active nginx)

if [ "$nginx_status" != "active" ]; then
  echo "Nginx is not active. Starting Nginx..."
  sudo service start nginx
else
  echo "Nginx is already active."
fi

# Check if Nginx is listening on port 80
nginx_listen=$(netstat -tuln | grep LISTEN | grep ":80")

if [ -z "$nginx_listen" ]; then
  echo "Configuring Nginx to listen on port 80..."
  # Update Nginx configuration to listen on port 80
  sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

  # Restart Nginx
sudo service restart nginx

  echo "Nginx is now listening on port 80."
else
  echo "Nginx is already listening on port 80."
fi

