#!/usr/bin/env bash
#  what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/defaultsudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sodo service nginx restart
rm /run/nginx.pid
