#!/usr/bin/env bash
# This script is displaying the story of passwd

while IFS=: read -r username password userid gid useridinfo home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"

done < /etc/passwd
