#!/usr/bin/env bash
# bash script to help reload gunicorn

# Replace 'myproject' with the name of your Gunicorn systemd service
SERVICE_NAME="gunicorn.service"

# Reload the Gunicorn service
sudo systemctl reload $SERVICE_NAME

# Check the status of the service
sudo systemctl status $SERVICE_NAME

