#!/usr/bin/env bash
# Name for the private key
KEY_NAME="school"

# Number of bits for the key
BITS=4096

# Passphrase for the key
PASSPHRASE="betty"

# Generate the RSA key pair with the specified requirements
ssh-keygen -t rsa -b $BITS -C "RSA key for $KEY_NAME" -N "$PASSPHRASE" -f "$KEY_NAME"

